-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1200@60.10", position = "4576x0", scale = 1.00, vrr = 1 })
hl.monitor({ output = "DP-6", mode = "1920x1080@60.00", position = "736x0", scale = 1.00 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "2656x64", scale = 1.00 })
